### ISSUE TITLE
userparameter conf not deleted 

### ISSUE THREAD

**Issue by istoph** [zabbix-deb/zabbix-check-ksm#1]
The CI reports that the parameter ksm is executed twice when updating from 1:1.3 to 1:1.4. 

```
zabbix_agentd [1600]: ERROR: cannot add user parameter "ksm[*],/usr/lib/zabbix-check/bin/zabbix-check-ksm $1": key "ksm" already exists
```

This probably does not delete the old config file when updating.

```
-etc/zabbix/zabbix_agentd.d/userparameter_ksm.conf
+etc/zabbix/zabbix_agentd.d/zabbix-check-ksm.conf
```

Look at the following commit cd41455f6624515e03b1da9b2f4612451ccecd86

**Comment by imolein** [comment]
Added zabbix-check-ksm.maintscript which should take care of the old userparameter conf file
